### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by maikeloni** [ickerwx/tcpproxy#10]
Due to the character `/` in the line `self.name = __file__.rsplit('/', 1)[1].split('.')[0]` in the modules, the tool does not work on windows.

**Comment by ickerwx** [comment]
I haven't ever tried the proxy on Windows :sweat_smile:

I think using `os.sep` or whatever it is called should be the better solution. Still better would be to remove this stupid housekeeping code altogether, but it works...

I will see if I can find the time to replace the hard-coded separator with platform-agnostic code over the weekend.

**Comment by Nable80** [comment]
Oh, man, you should just try using os.path.* for such operations. One can use ``import os.path as op`` pattern to make the code even more compact. E.g. ``op.splitext(op.basename(__file__))[0]`` should do the trick and looks a bit less cryptic than the above-mentioned construction.
_I'm not a Windows user either._

**Comment by ickerwx** [comment]
Yep, sounds like a good solution. I'm only on my phone for the next couple of days, so feel free to send a pull request and I will happily merge it. If not, I will do it when I'm in front of a computer again.

**Comment by ickerwx** [comment]
@maikeloni I implemented the fix as suggested by @Nable80, but I don't have a Windows installation ready to test it. It works fine on Linux, so I assume it should do so on Win as well.

Please let me know if it's okay so that I can close this. Should you run into more issues (and you probably will, this was hacked together with no regard to any other OS than Linux) please open a new issue.

Thanks a lot.

**Comment by maikeloni** [comment]
It seems to work fine. Thanks for the fix!

**Comment by ickerwx** [comment]
👍

**Comment by Nable80** [comment]
@ickerwx 
There's at least one more place to change (readme.md), see search results: https://github.com/ickerwx/tcpproxy/search?utf8=%E2%9C%93&q=rsplit&type=
By the way, thank you for the quick reaction and for this whole work!

**Comment by ickerwx** [comment]
Yeah, the readme is at the same time the most important file (as it is the first file seen on the project page), but also the ugly stepchild that I hate to constantly redo. I'll get to it sooner or later, thanks.
