### ISSUE TITLE
Port proxy to python3

### ISSUE THREAD

**Issue by ickerwx** [ickerwx/tcpproxy#12]
It's probably not difficult, but somebody has to do it.

**Comment by bjorns163** [comment]
Do you want this to be backwords compatible with python2? 
Have 4 moduels left to test, the rest are working

- size 
- javaxml
-size404 
-digestdowngrade

**Comment by ickerwx** [comment]
javaxml doesn't work at the moment, you can't test it. I don't need backwards compatibility.

Thanks for the work.

**Comment by ickerwx** [comment]
Done for now, but needs more testing.
