### ISSUE TITLE
Uncaught exception in `start_proxy_thread`

### ISSUE THREAD

**Issue by ickerwx** [ickerwx/tcpproxy#15]
Hi,
module is running fine, but i get some "connection refused" from china cloud that results in 
```
47.91.242.120:10013 - Connection refused
47.91.242.120:10013 - Connection refused
Exception in thread Thread-54576:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./tcpproxy.py", line 270, in start_proxy_thread
    peer = sock.getpeername()
OSError: [Errno 107] Transport endpoint is not connected
```
perhaps you could add a timestamp when this happens or add syslog support (new feature request ;-) )

But, for this issue / feature request i consider the module mqtt working fine.

regards Martin

_Originally posted by @MatzeJoerling in https://github.com/ickerwx/tcpproxy/issues/14#issuecomment-634553689_

**Comment by ickerwx** [comment]
This tool was developed with a specific purpose: application security testing, therefore there are probably a lot of issues that I never faced because the proxy was never intended to run for a longer period of time, or permanently, doing some kind of traffic multiplexing.

I'm not saying you're using it wrong, there is clearly a bug here, I just want you to be aware that your use-case was never considered by me and you will most likely run into more problems down the road. I'll fix them as good as I can when they pop up :smile:

**Comment by MatzeJoerling** [comment]
Hi,
sorry for that, but i googled for tcpproxy and got a bunch of fat, complex software for my little problem. your software looks small, good, easy and did the job (intercepting chinese cloud data) very well from the 1st minute. also extending with mqtt was fast and well implemented, thanks for that.

perhabs you could build a general purpose CN cloud intercepting proxy ;-)

thanks for fixing
 regards M.

**Comment by ickerwx** [comment]
Please don't apologize, this wasn't meant to be taken this way, I am very glad that my little project is useful to you. I just said this so you could better understand why you might run into more bugs in the future. I never thought it would used the way you use it, so I didn't really test it the way you do. That means there will be more bugs like this, please report them and I will fix them when I have the time.

This particular bug is kind of weird, though, I don't understand why this particular error happens, I will need some time to build tests and reproduce this issue.

Does this error happen under some specific circumstances, or is it more or less random? And does the proxy crash, or is it working okay after you see this error?

**Comment by MatzeJoerling** [comment]
Hi,
because of missinig timestamp i cant say when it happens, but it happens even if there is no traffic! And it looks like random crashes. 
The protocol that the CN cloud devices talk is pretty easy.

can i start the proxy in some kind of debug mode / environment to get some useful output?

**Comment by ickerwx** [comment]
Try to run the latest commit a094445 for a while and let me know if anything doesn't work as you expect it.

**Comment by MatzeJoerling** [comment]
Hm, downloaded master and run it, was that ok? Or do i need to download anything special.
Logs from 18h attached. 
[stderr.log](https://github.com/ickerwx/tcpproxy/files/4715715/stderr.log)

**Comment by ickerwx** [comment]
It's okay, it was what I wanted you to do. I added some code to better deal with the error in the first message in this issue, the errrors in your log are from a different part of the code. I have created a new branch issue_15. Please use this branch and let it run again.

I added some more error handling and timestamps so I can try to maybe get a better idea of what's happening.
This process is a little tedious and it's a rather annoying way of trying to fix this, but it's the best I can come up with, I don't have much time at the moment.

**Comment by MatzeJoerling** [comment]
hi,
so far only connection refused, looks like cloud admins did some maintenance.
Site down for 10min. will attach log and observe further.

regards M.
[stderr_issue15.log](https://github.com/ickerwx/tcpproxy/files/4721140/stderr_issue15.log)

**Comment by MatzeJoerling** [comment]
same today, only connection refused in some 10min timeframes. no further error messages ...

**Comment by ickerwx** [comment]
Alright, thanks for the feedback. I can' do much about the connection issues, but at least we got rid of the exception messages and traces.
I'll merge this into master soon, feel free to switch back to that branch and also please report anything else you find.
