### ISSUE TITLE
[Feature request] acting as a SOCKS5 proxy server?

### ISSUE THREAD

**Issue by shunf4** [ickerwx/tcpproxy#24]
I use tcpproxy to do MitM attack on SSL protected TCP connections (to a fixed destination IP:port) and it works well.

It would be better that it can act as a SOCKS5 proxy server, so that it can intercept all connections to any IP:port initiated by an application as long as this application respects the proxy server settings.

Is this doable, or there is a better alternative?

**Comment by shunf4** [comment]
Here is my implementation for my personal use:

https://github.com/shunf4/tcpproxy/tree/for_upstream

Diff: https://github.com/ickerwx/tcpproxy/compare/master...shunf4:for_upstream?expand=1

**Comment by ptitdoc** [comment]
Also check the current pull requests. You have ways to achieve that using NAT setup (transparent proxying) instead of SOCKS.

**Comment by ickerwx** [comment]
Hi @shunf4,

it looks like @ptitdoc has implemented a nice solution. Check the branch ptitdoc-ethicomputing-merge and see if this does what you need. Right now this will probably not work and require a little bugfixing.
