### ISSUE TITLE
Cannot get tcpproxy to use custom server certificate

### ISSUE THREAD

**Issue by Strider3000** [ickerwx/tcpproxy#25]
Tried using -sc and -sk pointing to mitm.pem and tcpproxy always returns the target server cert instead.
Is this feature broken?
If not could someone please post the correct command.

**Comment by ickerwx** [comment]
It should work just fine. If you are using the supplied dummy cert in `mitm.pem` you don't even have to specify `-sc/-sk`, just use the `--ssl` parameter. Which command do you use to start the proxy?

**Comment by Strider3000** [comment]
Facepalm... I never used the -s switch, only -sc and -sk. The following command works great on Windoz:
python tcpproxy.py -ti HOSTNAME -tp 443 -li LOCALIP -lp 443 -pt HTTP -im size -s
Looks like its working now.
Thanks for the fast feedback!

**Comment by ickerwx** [comment]
Great, happy to hear you got it working. Just so you understand it a little better, `-s` enables TLS, and the switches you mentioned are used when you want to specifiy a different key/certificate.

Have fun, and if you write an interesting module, feel free to open up a pull request.
