### ISSUE TITLE
Share value between Input and Output Module

### ISSUE THREAD

**Issue by davidmann4** [ickerwx/tcpproxy#30]
I would like to share a variable with the input and output module

I receive a value that has to be adjusted when the client sends the next packet. Any Idea how to solve this? 

Currently I write it into a file and read it again in the other module - it works for now but I guess there is a better way to do this :)

**Comment by ptitdoc** [comment]
Hello,

The input and output modules are creating different objects and there is no easy sharing facilities in the current master branch.

If you use the branch https://github.com/ickerwx/tcpproxy/tree/ptitdoc-ethicomputing-merge, you have two options:
- You can use the `self.conn` object in your plugin if you inherit `BaseModule` to share some information (https://github.com/ickerwx/tcpproxy/blob/ptitdoc-ethicomputing-merge/conndata.py). If the information is just a simple tag, you can use `self.conn.add_tag("mytagname")`, and `self.conn.get_tags()` which are already existing.
- Another option is using file as you are doing, or in some of my code, I store information on redis (like using redis as a certificate cache in https://github.com/ickerwx/tcpproxy/blob/30ea295975c9b4496aaa6b1026bc0b25af3ff38b/proxymodules/sslupgrade.py#L264

**Comment by davidmann4** [comment]
ohh, interesting will try it! is self.conn session based? (never tried to run multiple sessions yet)

**Comment by ptitdoc** [comment]
It's connection based. I don't know what do you mean by session?If you start two instance of tcpproxy it won't be shared between instances. You will have to use files or other means such as redis to share data. -------- Message original --------De : David Mann ***@***.***>Date : lun. 29 mars 2021 à 10:20À : ickerwx/tcpproxy ***@***.***>Cc : ptitdoc ***@***.***>, Comment ***@***.***>Objet : Re: [ickerwx/tcpproxy] Share value between Input and Output Module (#30)
ohh, interesting will try it! is self.conn session based? (never tried to run multiple sessions yet)

**Comment by davidmann4** [comment]
Program1  --->          tcpproxy     --->   target host
Program2  --->

I was talking about 2 connections to the same tcpproxy instance (like above)

**Comment by ptitdoc** [comment]
So it will be two different tcp connections with two different conn objects.

What is your use case ?
