### ISSUE TITLE
Indicate data direction in hexdump module

### ISSUE THREAD

**Issue by ishche** [ickerwx/tcpproxy#32]
It would really handy if there was an indication of data direction on hex dump. It's hard to understand if it's a line of inbound or outbound data.
It should not hard to implement. For example, it can be something like this:
```
--- a/proxymodules/hexdump.py
+++ b/proxymodules/hexdump.py
@@ -25,7 +25,7 @@ class Module:
             s = data[i:i + self.len]
             hexa = ' '.join(['%0*X' % (digits, x) for x in s])
             text = ''.join([chr(x) if 0x20 <= x < 0x7F else '.' for x in s])
-            result.append("%04X   %-*s   %s" % (i, self.len * (digits + 1), hexa, text))
+            result.append("%s %04X   %-*s   %s" % ("<" if self.incoming else ">", i, self.len * (digits + 1), hexa, text))
         print("\n".join(result))
         return data
```

**Comment by ickerwx** [comment]
Thanks a lot for trying out my little tool. This is implemented in a slightly different way when you use the `-v/--verbose` command line switch.

![direction-indicator](https://user-images.githubusercontent.com/7716530/118374485-9993a000-b5bc-11eb-93d4-44da8b9dc3e8.png)

If you use more than one module you will get this direction indicator in front of every module, but I'd rather not see this inside a single module. So far, using the verbose switch was alright. Would that be an acceptable solution?

**Comment by ishche** [comment]
Sure, it's perfect. Thank you!
