### ISSUE TITLE
Dropped packets when using SOCKS

### ISSUE THREAD

**Issue by ptitdoc** [ickerwx/tcpproxy#33]
When using SOCKS proxy for incoming traffic (using the branch https://github.com/ickerwx/tcpproxy/tree/ptitdoc-ethicomputing-merge), I noticed that some connections are staled under heavy load.

I remember similar issue in the git log regarding big packets and required increasing the read buffer.

I'm still investigating this issue as neither the exact issue nor the cause has been identified.

**Comment by shunf4** [comment]
You can try my fork and see if the problem exists: https://github.com/shunf4/tcpproxy/tree/shunf4_mod_ng

This fork didn't do many changes to the original main branch.

**Comment by ickerwx** [comment]
Sorry, I can't reproduce it and since this is quite old, I guess it's also no longer relevant for you.
