### ISSUE TITLE
Support for multiple clients (sockets)

### ISSUE THREAD

**Issue by michaelchandrag** [ickerwx/tcpproxy#36]
Hi, I have tried this tools and it works amazingly with 1 client connecting to the proxy. Is this tools support for 1 connection to the server while the proxy open for multiple clients also the message from server send to the related client? I wanted to make sure since I can't do it right now with more than 1 client.

**Comment by ickerwx** [comment]
Hello Michael,

I just tested a small multiple client scenario and it worked well.

![threeclients](https://user-images.githubusercontent.com/7716530/146691370-5c2e6f17-5ce9-4582-91cf-07b26a9ebbfa.png)

In the pic you see three clients (terminals 1-3), connecting to the proxy in terminal 4, and a webserver in terminal 5. The clients request three different resources, the webserver receives these requests and all clients receive their respective answer.

Can you please describe your actual setup in a bit more detail?

**Comment by ickerwx** [comment]
@michaelchandrag Do you need help here anymore? I'm going to close this in a day or two if I don't hear from you.
