### ISSUE TITLE
Been wondering, remote?

### ISSUE THREAD

**Issue by jhave21** [ickerwx/tcpproxy#5]
Hello, great coding style, loved it,
wanna ask whether this works on remote PCs

like my thick client is on a remote PC (different network) communicating on the server (different network) using a simple socket.

**Comment by ickerwx** [comment]
I see no reason it should not work. If you have an SSH session on your remote PC, you can just run the proxy there.

**Comment by ickerwx** [comment]
Any questions left? If not, I'm gonna close this tomorrow.
