### ISSUE TITLE
License

### ISSUE THREAD

**Issue by AnnaHsen** [ickerwx/tcpproxy#8]
Hi!

We are a group of undergraduate students writing a project on TLS/Cryptography.
We stumbled upon your implementation here, and it would be very useful for getting our project to work. However, you do not have a specified public use license, which means that the default license is All Rights Reserved. We would be really happy if you would give us permission to use your project as a resource or add a public use license such as GNU GPL.

Thank you very much!
Kind regards

**Comment by ickerwx** [comment]
Good luck with your project, I'd love to see what you'll come up with.

I put the project under the MIT License, I believe this should be okay for you.

**Comment by AnnaHsen** [comment]
Thank you so much! :D
